language: ruby
script: "bundle exec rake"
rvm:
  - 2.4.5
before_install:
  - gem install bundler -v '< 2'
env:
  - PUPPET_GEM_VERSION='4.3.1'
matrix:
  allow_failures:
    - env: PUPPET_GEM_VESRION="4.3.1"
