language: ruby
script: "bundle exec rake"
dist: precise
rvm:
  - 1.9.3
before_install:
  - gem install bundler -v '< 2'
env:
  - PUPPET_GEM_VERSION='3.6.2'
matrix:
  allow_failures:
    - env: PUPPET_GEM_VESRION="3.6.2"
